class MQTTConstants:
    AT_MOST_ONCE = 0
    AT_LEAST_ONCE = 1
    EXACTLY_ONCE = 2

    MESSAGE_TYPE_LENGTH = 1
    MESSAGE_FIXED_HEADER_MINIMUM_SIZE = 2

    PUBLISH_TIMEOUT = 10
    KEEPALIVE_FACTOR = 2


